### ISSUE TITLE
HeroBackground positioning

### ISSUE THREAD

**Issue by chartgerink** [libscie/libscieverse#4]
Currently, the HeroBackground is positioned based on the `libscie.org` one - absolute and with a top depending on viewWidth.

For example:

```css
HeroBackground {
  display: absolute;
  top: 150px;
}
```

This does not really scale to other types of backgrounds that may need `top: 0px`.

This is an open issue that requires some planning and testing with the various screenwidths and pages to make it work.
